### ISSUE TITLE
Select installation language of the League of Legends BETA Client

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/Scripts#180]
During the installation of the League of Legends BETA client I couldn't select the language of client. It automatically installed the english version.
I believe it would be better to give the user the choice, which language he wants to install.
Maybe it's possible to ask the user if he wants to do a fast installation or an "advanced" installation, where he can set such options?

**Comment by plata** [comment]
This is caused by the "/q" option for the installation. If you remove this, you should see the installation windows.
I don't think it makes sense to ask for fast/advanced installation. However, you can do that by showing a menu step in the wizard.

**Comment by madoar** [comment]
Is there a way to see the script in POL 5 before you execute it? It would be quite nice if there was an editor mode where you can do some local changes to a script directly before you execute it (changes like removing the "/q" option).

**Comment by plata** [comment]
I'm not sure we should provide this. The scripts should be written in a way so that they can be used out of the box. If you need to change something locally, you should use a LocalApplicationSource.

For the "/q" option: I suggest to completely remove it from the script. We can never know what implicit settings are used with the option (e.g. language). Additionally, people might wonder where the installation dialog is gone.

**Comment by plata** [comment]
@madoar can this be closed?

**Comment by madoar** [comment]
Not yet, I think. We still need to remove the "/q" option.

**Comment by plata** [comment]
Could you do that?

**Comment by plata** [comment]
@madoar any update on this one?
